# Generated by Django 4.2.7 on 2026-09-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasiyici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Taşıyıcı Kodu')),
                ('ad', models.CharField(max_length=200, verbose_name='Firma/Şahıs Adı')),
                ('tipi', models.CharField(choices=[('firma', 'Firma'), ('sahis', 'Şahıs'), ('kooperatif', 'Kooperatif')], default='firma', max_length=20, verbose_name='Tipi')),
                ('yetkili', models.CharField(blank=True, max_length=100, verbose_name='Yetkili Kişi')),
                ('telefon', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('vergi_dairesi', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('vergi_no', models.CharField(blank=True, max_length=20, verbose_name='Vergi No')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taşıyıcı',
                'verbose_name_plural': 'Taşıyıcılar',
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='fatura_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='Fatura No'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='fatura_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Fatura Tarihi'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='irsaliye_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='İrsaliye No'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='nereden',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nereden (Depo/OİM)'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='nereye',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nereye'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='odeme_durumu',
            field=models.CharField(choices=[('odenmedi', 'Ödenmedi'), ('kismi_odendi', 'Kısmi Ödendi'), ('tamamen_odendi', 'Tamamen Ödendi')], default='odenmedi', max_length=20, verbose_name='Ödeme Durumu'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='odeme_notu',
            field=models.TextField(blank=True, verbose_name='Ödeme Notu'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='odeme_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='odenen_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ödenen Tutar (TL)'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='tasima_birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Taşıma Birim Fiyatı (TL/m³)'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='tasima_toplam_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Taşıma Toplam Tutar (TL)'),
        ),
        migrations.CreateModel(
            name='TasiyiciArac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=50, verbose_name='Plaka')),
                ('arac_tipi', models.CharField(blank=True, max_length=100, verbose_name='Araç Tipi')),
                ('marka', models.CharField(blank=True, max_length=100, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('kapasite_m3', models.FloatField(blank=True, null=True, verbose_name='Kapasite (m³)')),
                ('sofor_adi', models.CharField(blank=True, max_length=100, verbose_name='Şoför Adı')),
                ('sofor_telefon', models.CharField(blank=True, max_length=15, verbose_name='Şoför Telefon')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tasiyici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='araclar', to='stok.tasiyici', verbose_name='Taşıyıcı')),
            ],
            options={
                'verbose_name': 'Taşıyıcı Aracı',
                'verbose_name_plural': 'Taşıyıcı Araçları',
                'unique_together': {('tasiyici', 'plaka')},
            },
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='tasiyici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sevkler', to='stok.tasiyici', verbose_name='Taşıyıcı'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='tasiyici_arac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sevkler', to='stok.tasiyiciarac', verbose_name='Araç'),
        ),
    ]
