# Generated by Django 4.2.7 on 2026-09-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_tasiyici_ihalesevk_fatura_no_ihalesevk_fatura_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasiyiciOdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odeme_tarihi', models.DateField(verbose_name='Ödeme Tarihi')),
                ('odeme_tutari', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ödeme Tutarı (TL)')),
                ('odeme_tipi', models.CharField(choices=[('nakit', 'Nakit'), ('havale', 'Havale/EFT'), ('cek', 'Çek'), ('senet', 'Senet')], default='havale', max_length=20, verbose_name='Ödeme Tipi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('sevk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odemeler', to='stok.ihalesevk', verbose_name='İhale Sevki')),
            ],
            options={
                'verbose_name': 'Taşıyıcı Ödemesi',
                'verbose_name_plural': 'Taşıyıcı Ödemeleri',
                'ordering': ['-odeme_tarihi'],
            },
        ),
    ]
