# Generated by Django 4.2.7 on 2026-10-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0003_tasiyiciodeme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihalesevk',
            name='odeme_durumu',
        ),
        migrations.RemoveField(
            model_name='ihalesevk',
            name='odeme_notu',
        ),
        migrations.RemoveField(
            model_name='ihalesevk',
            name='odeme_tarihi',
        ),
        migrations.RemoveField(
            model_name='ihalesevk',
            name='odenen_tutar',
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='tasima_odeme_durumu',
            field=models.CharField(choices=[('odenmedi', 'Ödenmedi'), ('kismi_odendi', 'Kısmi Ödendi'), ('tamamen_odendi', 'Tamamen Ödendi')], default='odenmedi', help_text='Otomatik hesaplanır (TasiyiciOdeme kayıtlarından)', max_length=20, verbose_name='Taşıma Ödeme Durumu'),
        ),
        migrations.AddField(
            model_name='ihalesevk',
            name='tasima_odenen_tutar',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Otomatik hesaplanır (TasiyiciOdeme toplamı)', max_digits=15, verbose_name='Taşımaya Ödenen (TL)'),
        ),
    ]
