# Generated by Django 4.2.7 on 2026-10-06 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stok', '0004_remove_ihalesevk_odeme_durumu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StokDevir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.IntegerField(verbose_name='Yıl')),
                ('ay', models.IntegerField(choices=[(1, 'Ocak'), (2, 'Şubat'), (3, 'Mart'), (4, 'Nisan'), (5, 'Mayıs'), (6, 'Haziran'), (7, 'Temmuz'), (8, 'Ağustos'), (9, 'Eylül'), (10, 'Ekim'), (11, 'Kasım'), (12, 'Aralık')], verbose_name='Ay')),
                ('devir_miktar', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Devir Miktarı (m³)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Stok Devir',
                'verbose_name_plural': 'Stok Devirleri',
                'ordering': ['-yil', '-ay'],
                'unique_together': {('yil', 'ay')},
            },
        ),
    ]
