# Generated by Django 4.2.7 on 2026-09-08 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_kodu', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Müşteri Kodu')),
                ('unvan', models.CharField(max_length=200, verbose_name='Ünvan')),
                ('vergi_dairesi', models.CharField(max_length=100, verbose_name='Vergi Dairesi')),
                ('vergi_no', models.CharField(max_length=10, verbose_name='Vergi No')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Posta')),
                ('yetkili', models.CharField(blank=True, max_length=100, verbose_name='Yetkili Kişi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satis_no', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Satış No')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('teslim_tarihi', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('miktar', models.FloatField(verbose_name='Miktar (m³)')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birim Fiyat (TL)')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Toplam Tutar')),
                ('durum', models.CharField(choices=[('teklif', 'Teklif'), ('onaylandi', 'Onaylandı'), ('hazirlaniyor', 'Hazırlanıyor'), ('sevk_edildi', 'Sevk Edildi'), ('teslim_edildi', 'Teslim Edildi'), ('iptal', 'İptal')], default='teklif', max_length=20, verbose_name='Durum')),
                ('odeme_durumu', models.CharField(choices=[('beklemede', 'Beklemede'), ('kismi', 'Kısmi Ödeme'), ('tamam', 'Tamamlandı'), ('gecikti', 'Gecikti')], default='beklemede', max_length=20, verbose_name='Ödeme Durumu')),
                ('irsaliye_no', models.CharField(blank=True, max_length=50, verbose_name='İrsaliye No')),
                ('fatura_no', models.CharField(blank=True, max_length=50, verbose_name='Fatura No')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siparis.musteri', verbose_name='Müşteri')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Satış',
                'verbose_name_plural': 'Satışlar',
                'ordering': ['-siparis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siparis_no', models.CharField(max_length=50, unique=True, verbose_name='Sipariş No')),
                ('miktar', models.FloatField(verbose_name='Miktar (m³)')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birim Fiyat')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Toplam Tutar')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('isleniyor', 'İşleniyor'), ('hazir', 'Hazır'), ('teslim_edildi', 'Teslim Edildi'), ('iptal', 'İptal')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('teslim_tarihi', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('musteri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siparis.musteri', verbose_name='Müşteri')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-siparis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SatisIade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iade_no', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='İade No')),
                ('iade_tarihi', models.DateField(auto_now_add=True, verbose_name='İade Tarihi')),
                ('miktar', models.FloatField(verbose_name='İade Miktarı (m³)')),
                ('sebep', models.TextField(verbose_name='İade Sebebi')),
                ('onaylandi_mi', models.BooleanField(default=False, verbose_name='Onaylandı mı?')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iadeler', to='siparis.satis', verbose_name='Satış')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Satış İadesi',
                'verbose_name_plural': 'Satış İadeleri',
                'ordering': ['-iade_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SatisDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.FloatField(verbose_name='Miktar (m³)')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birim Fiyat (TL)')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Toplam Tutar')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('satis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='siparis.satis', verbose_name='Satış')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stok.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Satış Detayı',
                'verbose_name_plural': 'Satış Detayları',
            },
        ),
    ]
