# Generated by Django 4.2.7 on 2026-09-08 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siparis', '0001_initial'),
        ('stok', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Banka Adı')),
                ('sube', models.CharField(max_length=200, verbose_name='Şube')),
                ('hesap_no', models.CharField(max_length=50, unique=True, verbose_name='Hesap No')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('hesap_tipi', models.CharField(choices=[('vadesiz', 'Vadesiz Mevduat'), ('vadeli', 'Vadeli Mevduat'), ('kredi', 'Kredi Hesabı')], default='vadesiz', max_length=20, verbose_name='Hesap Tipi')),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bakiye')),
                ('para_birimi', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Banka Hesabı',
                'verbose_name_plural': 'Banka Hesapları',
            },
        ),
        migrations.CreateModel(
            name='CariHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hesap_tipi', models.CharField(choices=[('musteri', 'Müşteri'), ('tedarikci', 'Tedarikçi')], max_length=20, verbose_name='Hesap Tipi')),
                ('bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bakiye')),
                ('borc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Borç')),
                ('alacak', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Alacak')),
                ('limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kredi Limiti')),
                ('risk_orani', models.FloatField(default=0, verbose_name='Risk Oranı (%)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('musteri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siparis.musteri', verbose_name='Müşteri')),
                ('tedarikci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stok.tedarikci', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Cari Hesap',
                'verbose_name_plural': 'Cari Hesaplar',
            },
        ),
        migrations.CreateModel(
            name='CariHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('borc', 'Borç (Müşteri Borcu)'), ('alacak', 'Alacak (Müşteri Ödemesi)')], max_length=20, verbose_name='Hareket Tipi')),
                ('kaynak_tipi', models.CharField(choices=[('fatura', 'Fatura'), ('tahsilat', 'Tahsilat'), ('odeme', 'Ödeme'), ('diger', 'Diğer')], max_length=20, verbose_name='Kaynak Tipi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (TL)')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('vade_tarihi', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('belge_no', models.CharField(blank=True, max_length=50, verbose_name='Belge No')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cari_hareket', to='finans.carihesap', verbose_name='Cari Hesap')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Cari Hareket',
                'verbose_name_plural': 'Cari Hareketler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='BankaHareket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hareket_tipi', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış')], max_length=10, verbose_name='Hareket Tipi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('banka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banka_hareket', to='finans.banka', verbose_name='Banka')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
            ],
            options={
                'verbose_name': 'Banka Hareketi',
                'verbose_name_plural': 'Banka Hareketleri',
                'ordering': ['-tarih'],
            },
        ),
    ]
