# Generated by Django 4.2.7 on 2026-09-08 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Departman Adı')),
                ('kod', models.CharField(max_length=20, unique=True, verbose_name='Departman Kodu')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicil_no', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Sicil No')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('tc_kimlik', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('dogum_tarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('dogum_yeri', models.CharField(blank=True, max_length=100, verbose_name='Doğum Yeri')),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('kadin', 'Kadın')], max_length=10, verbose_name='Cinsiyet')),
                ('kan_grubu', models.CharField(blank=True, choices=[('A Rh+', 'A Rh+'), ('A Rh-', 'A Rh-'), ('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-'), ('AB Rh+', 'AB Rh+'), ('AB Rh-', 'AB Rh-'), ('0 Rh+', '0 Rh+'), ('0 Rh-', '0 Rh-')], max_length=10, verbose_name='Kan Grubu')),
                ('medeni_durum', models.CharField(blank=True, choices=[('bekar', 'Bekar'), ('evli', 'Evli'), ('bosanmis', 'Boşanmış'), ('dul', 'Dul')], max_length=20, verbose_name='Medeni Durum')),
                ('cocuk_sayisi', models.IntegerField(default=0, verbose_name='Çocuk Sayısı')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('cep_telefonu', models.CharField(blank=True, max_length=15, verbose_name='Cep Telefonu')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Posta')),
                ('adres', models.TextField(verbose_name='Adres')),
                ('acil_durum_kisi', models.CharField(blank=True, max_length=100, verbose_name='Acil Durum Kişisi')),
                ('acil_durum_telefon', models.CharField(blank=True, max_length=15, verbose_name='Acil Durum Telefonu')),
                ('unvan', models.CharField(blank=True, max_length=100, verbose_name='Ünvan')),
                ('ise_giris_tarihi', models.DateField(verbose_name='İşe Giriş Tarihi')),
                ('isten_cikis_tarihi', models.DateField(blank=True, null=True, verbose_name='İşten Çıkış Tarihi')),
                ('calisma_durumu', models.CharField(choices=[('aktif', 'Aktif'), ('izinli', 'İzinli'), ('raporlu', 'Raporlu'), ('cikis', 'Çıkış Yaptı')], default='aktif', max_length=20, verbose_name='Çalışma Durumu')),
                ('maas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maaş (TL)')),
                ('maas_birimi', models.CharField(default='aylik', max_length=20, verbose_name='Maaş Birimi')),
                ('ek_odeme', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ek Ödeme (TL)')),
                ('prim_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prim Oranı (%)')),
                ('egitim_durumu', models.CharField(blank=True, choices=[('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('onlisans', 'Ön Lisans'), ('lisans', 'Lisans'), ('yuksek_lisans', 'Yüksek Lisans'), ('doktora', 'Doktora')], max_length=20, verbose_name='Eğitim Durumu')),
                ('okul', models.CharField(blank=True, max_length=200, verbose_name='Mezun Olunan Okul')),
                ('bolum', models.CharField(blank=True, max_length=200, verbose_name='Bölüm')),
                ('mezuniyet_yili', models.IntegerField(blank=True, null=True, verbose_name='Mezuniyet Yılı')),
                ('ehliyet', models.CharField(blank=True, max_length=50, verbose_name='Ehliyet')),
                ('yabanci_dil', models.CharField(blank=True, max_length=100, verbose_name='Yabancı Dil')),
                ('bildigi_diller', models.TextField(blank=True, verbose_name='Bildiği Diller')),
                ('sertifikalar', models.TextField(blank=True, verbose_name='Sertifikalar')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('departman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personel.departman', verbose_name='Departman')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturulan_personel', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('user', models.OneToOneField(blank=True, help_text='Sisteme giriş yapacak kullanıcı hesabı', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Hesabı')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'ordering': ['ad', 'soyad'],
            },
        ),
        migrations.CreateModel(
            name='Izin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izin_tipi', models.CharField(choices=[('yillik', 'Yıllık İzin'), ('hastalik', 'Hastalık İzni'), ('mazeret', 'Mazeret İzni'), ('dogum', 'Doğum İzni'), ('olum', 'Ölüm İzni'), ('evlilik', 'Evlilik İzni'), ('ucretsiz', 'Ücretsiz İzin'), ('diger', 'Diğer')], max_length=20, verbose_name='İzin Tipi')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('gun_sayisi', models.IntegerField(verbose_name='Gün Sayısı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('beklemede', 'Beklemede'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('iptal', 'İptal')], default='beklemede', max_length=20, verbose_name='Durum')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylanan_izinler', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izinler', to='personel.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'İzin',
                'verbose_name_plural': 'İzinler',
                'ordering': ['-baslangic_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Vardiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardiya_tipi', models.CharField(choices=[('sabah', 'Sabah Vardiyası (08:00-16:00)'), ('aksam', 'Akşam Vardiyası (16:00-00:00)'), ('gece', 'Gece Vardiyası (00:00-08:00)'), ('normal', 'Normal Mesai (09:00-18:00)')], max_length=20, verbose_name='Vardiya Tipi')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('baslangic_saati', models.TimeField(verbose_name='Başlangıç Saati')),
                ('bitis_saati', models.TimeField(verbose_name='Bitiş Saati')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vardiyalar', to='personel.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Vardiya',
                'verbose_name_plural': 'Vardiyalar',
                'ordering': ['-tarih', 'personel'],
                'unique_together': {('personel', 'tarih')},
            },
        ),
        migrations.CreateModel(
            name='MesaiTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('gelis_saati', models.TimeField(verbose_name='Geliş Saati')),
                ('cikis_saati', models.TimeField(blank=True, null=True, verbose_name='Çıkış Saati')),
                ('toplam_calisma', models.DurationField(blank=True, null=True, verbose_name='Toplam Çalışma')),
                ('fazla_mesai', models.DurationField(blank=True, null=True, verbose_name='Fazla Mesai')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesailer', to='personel.personel', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Mesai Takibi',
                'verbose_name_plural': 'Mesai Takipleri',
                'ordering': ['-tarih', 'personel'],
                'unique_together': {('personel', 'tarih')},
            },
        ),
    ]
